name: Build and Push to Docker Hub

on:
  push:
    paths:
      - 'src/**'
      - 'api/**'
      - 'Dockerfile'
      - 'requirements.txt'
      - '.github/workflows/docker-push.yml'

  workflow_run:
    workflows: ["Train ML Model"]
    types:
      - completed

jobs:
  build:
    if: github.event_name == 'push' || github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    # If triggered via workflow_run, download model
    - name: Download model artifact
      if: github.event_name == 'workflow_run'
      uses: actions/download-artifact@v4
      with:
        name: trained-model
        path: model/

    # Ensure model exists
    - name: Check model availability
      run: |
        if [ ! -f model/latest_model.pkl ]; then
          echo "Model not found. Using previous or default model."
        fi


      # Log in to Docker Hub (using username + access token as password)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker image with 2 tags: latest + commit SHA
    - name: Build Docker Image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/my-app
        GIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker build -t $IMAGE_NAME:latest -t $IMAGE_NAME:$GIT_SHA .

      # Push both tags
    - name: Push Docker Image
      run: |
        IMAGE_NAME=${{ secrets.DOCKER_USERNAME }}/my-app
        GIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker push $IMAGE_NAME:latest
        docker push $IMAGE_NAME:$GIT_SHA

